"""Generates the seek-bar wave and play/pause morph resources (run once; output is checked in).

The wave is drawn as a *mask*: a panel-coloured rectangle with a sine-shaped hole.
Whatever sits underneath (the album-coloured gradient) shows through the hole.
This lets the launcher animate it on its RenderThread with a fixed-colour drawable,
while the colour itself stays dynamic (Android 11 RemoteViews can't tint ProgressBars).

The band is built from cubic Beziers (Hermite fit, exact tangents) instead of a dense
polyline: ~6x fewer path verbs to rasterise per frame, and a flat band with the *same*
command structure so the launcher can morph wave <-> flat on play / pause.
"""
import math, os

W, H = 280.0, 16.0          # viewport, roughly the seek bar size in dp on a Note 10
CY = H / 2
WAVELEN, AMP, HALF = 32.0, 2.6, 1.75
STEP = WAVELEN / 4          # one Bezier per quarter wave
PERIOD_MS = 2000            # time to scroll one wavelength (~16 dp/s)
GROW_MS, SHRINK_MS, ICON_MS = 520, 340, 280
PANEL = "#FF101012"
ROOT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")
A = 'xmlns:android="http://schemas.android.com/apk/res/android"'
X = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/gen_wave.py -->\n'

def f(v):
    s = ("%.2f" % v).rstrip("0").rstrip(".")
    return "0" if s == "-0" else s

def pt(p): return "%s,%s" % (f(p[0]), f(p[1]))

def edge(t, amp, side):
    """Point on the band's top (side=-1) or bottom (+1) edge, offset along the normal."""
    k = 2 * math.pi / WAVELEN
    y = CY + amp * math.sin(k * t)
    dy = amp * k * math.cos(k * t)
    n = math.hypot(dy, 1.0)
    return (t + side * (-dy / n) * HALF, y + side * (1.0 / n) * HALF)

def segments(amp, side):
    t0, t1 = -WAVELEN / 2, W + 1.5 * WAVELEN
    count = int(round((t1 - t0) / STEP))
    d = 1e-4
    segs = []
    for i in range(count):
        a, b = t0 + i * STEP, t0 + (i + 1) * STEP
        pa, pb = edge(a, amp, side), edge(b, amp, side)
        da = [(edge(a + d, amp, side)[j] - edge(a - d, amp, side)[j]) / (2 * d) for j in (0, 1)]
        db = [(edge(b + d, amp, side)[j] - edge(b - d, amp, side)[j]) / (2 * d) for j in (0, 1)]
        c1 = (pa[0] + da[0] * STEP / 3, pa[1] + da[1] * STEP / 3)
        c2 = (pb[0] - db[0] * STEP / 3, pb[1] - db[1] * STEP / 3)
        segs.append((pa, c1, c2, pb))
    return segs

def bez(s, u):
    return tuple((1-u)**3*s[0][j] + 3*(1-u)**2*u*s[1][j] + 3*(1-u)*u**2*s[2][j] + u**3*s[3][j] for j in (0, 1))

def band(amp):
    top, bot = segments(amp, -1), segments(amp, +1)
    out = ["M" + pt(top[0][0])]
    out += ["C%s %s %s" % (pt(s[1]), pt(s[2]), pt(s[3])) for s in top]
    out.append("L" + pt(bot[-1][3]))
    out += ["C%s %s %s" % (pt(s[2]), pt(s[1]), pt(s[0])) for s in reversed(bot)]
    return " ".join(out) + " Z"

def max_error():
    """Largest distance between the Bezier fit and the true offset curve, in dp."""
    worst = 0.0
    for side in (-1, 1):
        for s in segments(AMP, side):
            for u in (0.25, 0.5, 0.75):
                p = bez(s, u)
                # nearest true point by dense search around the segment
                a = s[0][0] - HALF - 1
                best = min(math.dist(p, edge(a + i * 0.002, AMP, side)) for i in range(int((STEP + 2 * HALF + 2) / 0.002)))
                worst = max(worst, best)
    return worst

# Mask outline: evenOdd, so the band becomes a hole. The rect outlives the scroll range.
MASK_RECT = "M-4,-4 H%s V%s H-4 Z" % (f(W + 2 * WAVELEN + 4), f(H + 4))
PATH_WAVE = MASK_RECT + " " + band(AMP)
PATH_FLAT = MASK_RECT + " " + band(0.0)

# Play / pause as two quads each, so one morphs into the other. The stroke (same colour,
# round joins) rounds the corners and is part of the icon's size.
PATH_PLAY = "M9,7 L13.25,9.5 L13.25,14.5 L9,17 Z M13.25,9.5 L17.5,12 L17.5,12 L13.25,14.5 Z"
PATH_PAUSE = "M7,6 L9,6 L9,18 L7,18 Z M15,6 L17,6 L17,18 L15,18 Z"
ICON = "#FF101012"

FILES = {
    "values/paths.xml": """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gen_wave.py -->
<resources>
    <string name="path_wave" translatable="false">%s</string>
    <string name="path_flat" translatable="false">%s</string>
    <string name="path_play" translatable="false">%s</string>
    <string name="path_pause" translatable="false">%s</string>
</resources>
""" % (PATH_WAVE, PATH_FLAT, PATH_PLAY, PATH_PAUSE),
}

def vector(path):
    return X + """<vector %s
    android:width="%sdp" android:height="%sdp"
    android:viewportWidth="%s" android:viewportHeight="%s">
    <group android:name="phase">
        <path android:name="band" android:fillColor="%s" android:fillType="evenOdd"
            android:pathData="@string/%s" />
    </group>
</vector>
""" % (A, f(W), f(H), f(W), f(H), PANEL, path)

# Grow starts flat, shrink starts at full amplitude: the vector's own pathData is what shows
# before the animation's first frame, so each must match its animation's start.
FILES["drawable/seek_wave_vec_flat.xml"] = vector("path_flat")
FILES["drawable/seek_wave_vec_full.xml"] = vector("path_wave")
FILES["drawable/seek_flat_mask.xml"] = X + """<vector %s
    android:width="%sdp" android:height="%sdp"
    android:viewportWidth="%s" android:viewportHeight="%s">
    <path android:fillColor="%s" android:fillType="evenOdd" android:pathData="@string/path_flat" />
</vector>
""" % (A, f(W), f(H), f(W), f(H), PANEL)

def anim(prop, vfrom, vto, dur, interp, vtype="floatType", repeat=False):
    rep = ('\n    android:repeatCount="infinite"\n    android:repeatMode="restart"' if repeat else "")
    return X + """<objectAnimator %s
    android:propertyName="%s"
    android:valueFrom="%s"
    android:valueTo="%s"
    android:valueType="%s"
    android:duration="%d"%s
    android:interpolator="%s" />
""" % (A, prop, vfrom, vto, vtype, dur, rep, interp)

LINEAR = "@android:anim/linear_interpolator"
DECEL = "@android:anim/decelerate_interpolator"
EMPH = "@android:interpolator/fast_out_slow_in"

# Scrolls exactly one wavelength, so the loop is seamless.
FILES["animator/wave_phase.xml"] = anim("translateX", 0, f(-WAVELEN), PERIOD_MS, LINEAR, repeat=True)
# On pause the wave coasts to a stop: a decelerate curve starts at twice its average
# speed, so covering half the linear distance matches the playing speed at t=0.
FILES["animator/wave_phase_stop.xml"] = anim(
    "translateX", 0, f(-WAVELEN * SHRINK_MS / PERIOD_MS / 2), SHRINK_MS, DECEL)
FILES["animator/wave_grow.xml"] = anim("pathData", "@string/path_flat", "@string/path_wave",
                                       GROW_MS, DECEL, "pathType")
FILES["animator/wave_shrink.xml"] = anim("pathData", "@string/path_wave", "@string/path_flat",
                                         SHRINK_MS, EMPH, "pathType")
FILES["animator/icon_to_pause.xml"] = anim("pathData", "@string/path_play", "@string/path_pause",
                                           ICON_MS, EMPH, "pathType")
FILES["animator/icon_to_play.xml"] = anim("pathData", "@string/path_pause", "@string/path_play",
                                          ICON_MS, EMPH, "pathType")

def avd(drawable, targets):
    body = "".join('    <target android:name="%s" android:animation="@animator/%s" />\n' % t for t in targets)
    return X + '<animated-vector %s\n    android:drawable="@drawable/%s">\n%s</animated-vector>\n' % (A, drawable, body)

FILES["drawable/seek_wave_grow.xml"] = avd("seek_wave_vec_flat", [("phase", "wave_phase"), ("band", "wave_grow")])
FILES["drawable/seek_wave_shrink.xml"] = avd("seek_wave_vec_full", [("phase", "wave_phase_stop"), ("band", "wave_shrink")])

def icon(path):
    return X + """<vector %s
    android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">
    <path android:name="icon" android:fillColor="%s" android:strokeColor="%s"
        android:strokeWidth="2" android:strokeLineJoin="round" android:pathData="@string/%s" />
</vector>
""" % (A, ICON, ICON, path)

FILES["drawable/ic_play.xml"] = icon("path_play")
FILES["drawable/ic_pause.xml"] = icon("path_pause")
FILES["drawable/avd_play_to_pause.xml"] = avd("ic_play", [("icon", "icon_to_pause")])
FILES["drawable/avd_pause_to_play.xml"] = avd("ic_pause", [("icon", "icon_to_play")])

for rel, body in FILES.items():
    p = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", newline="\n") as fh:
        fh.write(body)

# Superseded by the files above.
for old in ("drawable/seek_wave_mask.xml", "drawable/seek_wave_anim.xml", "drawable/seek_cover_vec.xml"):
    p = os.path.join(ROOT, old)
    if os.path.exists(p):
        os.remove(p)

print(len(FILES), "files, fit error %.4f dp, wave path %d chars" % (max_error(), len(PATH_WAVE)))
