"""Generates the seek-bar wave vector drawables (run once; output is checked in).

The wave is drawn as a *mask*: a panel-coloured rectangle with a sine-shaped hole.
Whatever sits underneath (the album-coloured gradient) shows through the hole.
This lets the launcher animate it on its RenderThread with a fixed-colour drawable,
while the colour itself stays dynamic (Android 11 RemoteViews can't tint ProgressBars).
"""
import math, os

W, H = 280.0, 14.0          # viewport, roughly the seek bar size in dp on a Note 10
WAVELEN, AMP, HALF = 28.0, 3.0, 1.5
PANEL = "#FF101012"
RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res", "drawable")

def f(v): return ("%.2f" % v).rstrip("0").rstrip(".")

def band():
    cy, k = H / 2, 2 * math.pi / WAVELEN
    xs = [i * 0.5 for i in range(int((W + WAVELEN) / 0.5) + 1)]
    top, bot = [], []
    for x in xs:
        y = cy + AMP * math.sin(k * x)
        dy = AMP * k * math.cos(k * x)
        n = math.hypot(dy, 1.0)
        nx, ny = -dy / n, 1.0 / n
        top.append((x - nx * HALF, y - ny * HALF))
        bot.append((x + nx * HALF, y + ny * HALF))
    pts = top + bot[::-1]
    return "M" + " L".join("%s,%s" % (f(x), f(y)) for x, y in pts) + " Z"

def rect(x0, y0, x1, y1):
    return "M%s,%s H%s V%s H%s Z" % (f(x0), f(y0), f(x1), f(y1), f(x0))

def vector(body, w=W):
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/gen_wave.py -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="%sdp" android:height="%sdp"\n'
            '    android:viewportWidth="%s" android:viewportHeight="%s">\n%s</vector>\n'
            % (f(w), f(H), f(w), f(H), body))

wave = ('    <group android:name="phase">\n'
        '        <path android:fillColor="%s" android:fillType="evenOdd"\n'
        '            android:pathData="%s %s"/>\n'
        '    </group>\n') % (PANEL, rect(0, 0, W + WAVELEN, H), band())
flat = ('    <path android:fillColor="%s" android:fillType="evenOdd"\n'
        '        android:pathData="%s %s"/>\n') % (PANEL, rect(0, 0, W, H), rect(0, H/2 - HALF, W, H/2 + HALF))
cover = ('    <path android:fillColor="%s" android:pathData="%s"/>\n'
         '    <path android:fillColor="#40FFFFFF" android:pathData="%s"/>\n') % (PANEL, rect(0, 0, W, H), rect(0, H/2 - 1, W, H/2 + 1))

os.makedirs(RES, exist_ok=True)
for name, body in (("seek_wave_mask", wave), ("seek_flat_mask", flat), ("seek_cover_vec", cover)):
    with open(os.path.join(RES, name + ".xml"), "w", newline="\n") as fh:
        fh.write(vector(body))
print("ok")
